Notes:
. The main advantage of copulas is that univariate
marginal distributions can be defined independently
from the joint behaviour of the variables involved. Hence, a
copula allows for modelling the dependence structure of random
variables regardless the family that the marginal distributions
belong to. Besides, joint return periods can be easily
estimated from copulas, which represents an additional benefit
as the study of joint return periods is essential to flood
frequency analysis.
The theory of copulas is based on the Sklar’s theorem
(Sklar, 1959), which in the case of a bivariate case can be
written in the form:
 H (x, y) = C{F (x), G(y)}, x, y ∈ R, (1)
where H (x, y) is the joint cumulative distribution function
of the random variables X and Y , F (x) and G(y) are the
marginal distribution functions of X and Y , respectively,
and the mapping function C : [0, 1]2 →[0, 1] is the copula
function.
Further details about copulas can be found in Joe (1997),
Nelsen (1999) and Salvadori et al. (2007).
Although copula models have been extensively applied in
other fields such as finance, they have been only recently applied
to model hydrological events such as floods, storms
and droughts. Overall, the Archimedean and extreme value
copula families are the most used in modelling flood variables.
The Archimedean copulas can be constructed easily
and, as a great deal of copulas belongs to this family, a broad
kind of dependence can be considered. Some authors used
Archimedean copulas such as the Frank copula (Favre et al.,
2004) or the Clayton copula (Shiau et al., 2006) to characterise
the dependence structure between peak and volume variables. 
Meanwhile, extreme value copulas have the advantage
that they are able to connect the extreme values of the
studied variables, which is very important in flood frequency
analysis. A lot of authors considered the Gumbel copula as
the copula that best represents the relation between peak and
volume (Zhang and Singh, 2006, among others).
Flood peak = Q, Volume = V, Discharge = R

```{r }
library(spcopula)
library(VineCopula)
library(evd)
library(MASS)
library(hexbin)

load("~/R/ASTDProject/simTriHydro.RData")
head(all_QVD)
str(all_QVD)
simTriHydro <- all_QVD[,-1]
head(simTriHydro)
colnames(simTriHydro) <- c("Peak","Volume", "Duration")
head(simTriHydro)
plot(simTriHydro)


# Compute the pseudo-observations for simTriHydro and check scatter plot to find correlations
hydro <- pobs(simTriHydro[])
plot(cbind(hydro[,1], hydro[,2]), cex=0.5, asp=1, xlab = "Peak", ylab = "Volume", main = "Pseudo Observation", col = "light blue")

# Fit different multivariate copulas to find their correlation and dependencies
gaussFit <- fitCopula(normalCopula(dim=3), hydro)
gaussFit
u1 = rCopula(500,normalCopula(coef(gaussFit),dim=3))
points(u1[,1],u1[,2],col = "red")

gumbFit <- fitCopula(gumbelCopula(dim=3), hydro)
gumbFit
plot(cbind(hydro[,1], hydro[,2]), cex=0.5, asp=1, xlab = "Peak", ylab = "Volume", main = "Pseudo Observation", col = "light blue")
u1 = rCopula(500,gumbelCopula(coef(gumbFit),dim=3))
points(u1[,1],u1[,2],col = "red")


clayFit <- fitCopula(claytonCopula(dim=3), hydro)
clayFit
plot(cbind(hydro[,1], hydro[,2]), cex=0.5, asp=1, xlab = "Peak", ylab = "Volume", main = "Pseudo Observation", col = "light blue")
u1 = rCopula(500,claytonCopula(coef(clayFit),dim=3))
points(u1[,1],u1[,2],col = "red")

franFit <- fitCopula(frankCopula(dim=3), hydro)
franFit
plot(cbind(hydro[,1], hydro[,2]), cex=0.5, asp=1, xlab = "Peak", ylab = "Volume", main = "Pseudo Observation", col = "light blue")
u1 = rCopula(500,frankCopula(coef(franFit),dim=3))
points(u1[,1],u1[,2],col = "red")

# Selects an appropriate bivariate copula family for peak & volume distribution

BiCopSelect(hydro[,1], hydro[,2])
RVC <- RVineStructureSelect(hydro)
RVineLogLik(hydro, RVC)$loglik

RVineTreePlot(hydro, RVC, edge.labels= c("family", "theotau"), tree = 1:3)

# Analysis of extremes for each univariate distribution
#Discharge: all_QVD$Qmax.mcs

qmaxGev <- fgev(simTriHydro$Peak)
AIC(qmaxGev)
qmaxExp <- fitdistr(simTriHydro$Peak, "exponential")
AIC(qmaxExp)
qmaxLogNorm <- fitdistr(simTriHydro$Peak, "log-normal")
AIC(qmaxLogNorm)
dqmax <- function(x)
  dgev(x, qmaxGev$estimate[1], qmaxGev$estimate[2], qmaxGev$estimate[3])

hist(simTriHydro$Peak, freq=F, n=20, ylim=c(0,0.01), main = "Histogram of simTriHydro$Peak")

curve(dqmax, add=T, col="red")

pqmax <- function(x)
  pgev(x, qmaxGev$estimate[1], qmaxGev$estimate[2], qmaxGev$estimate[3])


plot(ecdf(all_QVD$Qmax.mcs))
curve(pqmax, add=T, col="red")

# Total Volume: simTriHydro$Volume

volumeGev <- fgev(simTriHydro$Volume)
AIC(volumeGev)
volumeExp <- fitdistr(simTriHydro$Volume, "exponential")
AIC(volumeExp)
volumeLogNorm <- fitdistr(simTriHydro$Volume, "log-normal")
AIC(volumeLogNorm)
dvolume <- function(x)
  dexp(x, volumeExp$estimate)

hist(simTriHydro$Volume, freq=F, n=20, ylim=c(0,1e-6))
curve(dvolume, add=T, col="red")

pvolume <- function(x)
  pexp(x, volumeExp$estimate)

plot(ecdf(simTriHydro$Volume))
curve(pvolume, add=T, col="red")

# Duration: simTriHydro$Duration

durationGev <- fgev(simTriHydro$Duration)
AIC(durationGev)
durationExp <- fitdistr(simTriHydro$Duration, "exponential")
AIC(durationExp)
durationLogNorm <- fitdistr(simTriHydro$Duration, "log-normal")
AIC(durationLogNorm)
dduration <- function(x)
  dgev(x, durationGev$estimate[1], durationGev$estimate[2], durationGev$estimate[3]-0.15)

hist(all_QVD$Dur.h, freq=F, n=20)
curve(dduration, add=T, col="red")
pduration <- function(x)
  pgev(x, durationGev$estimate[1], durationGev$estimate[2], durationGev$estimate[3]-0.15)

plot(ecdf(simTriHydro$Duration))
curve(pduration, add=T, col="red")

# Calculate pseudo-observations (on (0,1)) for the multivariate distribution, combining the
# univariate distributions

unifHydro <- pqmax(simTriHydro$Peak)
unifHydro <- cbind(unifHydro, pduration(simTriHydro$Duration))
unifHydro <- cbind(unifHydro, pvolume(simTriHydro$Volume))
colnames(unifHydro) <- c("peak", "duration", "volume")

hexplom(unifHydro)

# fit a suitable bivariate copula to Qp and Vp

BiCopSelect(unifHydro[,1], unifHydro[,3])
cop13 <- copulaFromFamilyIndex(1, 0.7628, 0)
cop13
BiCopSelect(unifHydro[,1], unifHydro[,2])

# calculate some bivariate return period

smplT <- sample(nrow(unifHydro), 6)
OrRP <- 1/(1-pCopula(unifHydro[smplT,c(1,3)], cop13))
KRP <- kendallRP(cl = pCopula(unifHydro[smplT,c(1,3)], cop13), copula = cop13)
AndRP <- 1/(1-unifHydro[smplT,1]-unifHydro[smplT,3]+pCopula(unifHydro[smplT,c(1,3)], cop13))

round(cbind(OrRP, KRP, AndRP),2)

#  RP change when a Gaussian copula is used (tail dependence)

copGauss <- fitCopula(normalCopula(), unifHydro[,c(1,3)])@copula
OrRPGauss <- 1/(1-pCopula(unifHydro[smplT,c(1,3)], copGauss))
KRPGauss <- kendallRP(cl = pCopula(unifHydro[smplT,c(1,3)], copGauss), copula = cop13)
AndRPGauss <- 1/(1-unifHydro[smplT,1]-unifHydro[smplT,3]+pCopula(unifHydro[smplT,c(1,3)], copGauss))

round(cbind(OrRP, OrRPGauss, KRP, KRPGauss, AndRP, AndRPGauss),2)

# fit a vine copula to the trivariate data set

RVC <- RVineCopSelect(unifHydro, Matrix=matrix(c(1,3,2,
                                               0,2,3,
                                               0,0,3),3,3))

RVineTreePlot(unifHydro, RVC, edge.labels=c("family","theotau"))

RVineLogLik(unifHydro, RVC)$loglik

# calculate the trivariate OR return period

OrRVine <- 1/(1-pCopula(unifHydro[smplT,], vineCopula(RVC)))
round(OrRVine, 2)

# change in return period  when a trivariate Gaussian copula is used

Gauss3d <- fitCopula(normalCopula(rep(0.2,3), dim=3, dispstr="un"), unifHydro)
Gauss3d
OrGauss3d <- 1/(1-pCopula(unifHydro[smplT,], Gauss3d@copula))

round(cbind(OrRVine, OrGauss3d, OrRP),2)
```

